### ISSUE TITLE
Properly support application/json

### ISSUE THREAD

**Issue by WickyNilliams** [Brbb/graphql-rover#2]
Whilst you can enter a content-type header, the request body is still sent as plain text and not json.  Apollo server only supports json.

Also, I think this should be a dropdown (options `applicaiton/graphql` and `applicaiton/json`), rather than a text field since there are a limited number of valid content-types for graphql (are there more beyond those two?)

**Comment by Brbb** [comment]
What would you send as request body? Always the introspection query as Rover is meant to do, or do you have any other idea?

**Comment by WickyNilliams** [comment]
Always the introspection query but the body should be valid JSON with a `query` property:

```json
{
  "query" : "..."
}
```

Graphiql sends requests in this format

**Comment by Brbb** [comment]
I've added a couple of things to manage the request, let me know if you find it good enough.

**Comment by WickyNilliams** [comment]
Seems to work
