### ISSUE TITLE
Change default endpoint to one that supports https

### ISSUE THREAD

**Issue by WickyNilliams** [Brbb/graphql-rover#4]
Current endpoint is blocked because of mixed content warnings. You should use a default endpoint that supports https

**Comment by Brbb** [comment]
Yeah, the Pokémon endpoint has http and I would like to find one open with https, or use a throwaway Auth Key. Suggestions?

**Comment by WickyNilliams** [comment]
Github? Or you could create your own with graph.cool? You might hit request limits with that though. Some other options here: https://github.com/APIs-guru/graphql-apis

**Comment by WickyNilliams** [comment]
Another option is to mock the server with graphql-tools?

**Comment by Brbb** [comment]
Done, I close the issue. The demo now works with an HTTPs endpoint representing the GraphQL European Conference schema.
